# example netlify.toml
[build]
  command = "npm run netlify dev"
  functions = "netlify/functions"
  publish = "."
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.


  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://docs.netlify.com/configure-builds/file-based-configuration/
